# Generated by Django 4.0.2 on 2023-03-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PAndWTBTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('leader_name', models.CharField(max_length=22)),
                ('leader_roll_no', models.CharField(max_length=9)),
                ('leader_thapar_email', models.CharField(max_length=50)),
                ('leader_phone_number', models.CharField(max_length=12)),
                ('teammate1_name', models.CharField(max_length=22)),
                ('teammate1_roll_no', models.CharField(max_length=9)),
                ('teammate1_thapar_email', models.CharField(max_length=50)),
                ('teammate2_name', models.CharField(max_length=22)),
                ('teammate2_roll_no', models.CharField(max_length=9)),
                ('teammate2_thapar_email', models.CharField(max_length=50)),
            ],
        ),
    ]
