# Generated by Django 4.0.2 on 2023-03-01 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_pandwtbteam_leader_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PAndWTBTeam',
            new_name='PTeam',
        ),
    ]
