# Generated by Django 4.0.2 on 2023-03-01 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pandwtbteam',
            name='leader_phone_number',
        ),
    ]
