# Generated by Django 4.0.2 on 2023-03-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_pandwtbteam_pteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClownCanard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('leader_name', models.CharField(max_length=22)),
                ('leader_roll_no', models.CharField(max_length=9)),
                ('leader_thapar_email', models.CharField(max_length=50)),
                ('teammate1_name', models.CharField(blank=True, default='', max_length=22, null=True)),
                ('teammate1_roll_no', models.CharField(blank=True, default='', max_length=9, null=True)),
                ('teammate1_thapar_email', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('teammate2_name', models.CharField(blank=True, default='', max_length=22, null=True)),
                ('teammate2_roll_no', models.CharField(blank=True, default='', max_length=9, null=True)),
                ('teammate2_thapar_email', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeOClock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('leader_name', models.CharField(max_length=22)),
                ('leader_roll_no', models.CharField(max_length=9)),
                ('leader_thapar_email', models.CharField(max_length=50)),
                ('teammate1_name', models.CharField(blank=True, default='', max_length=22, null=True)),
                ('teammate1_roll_no', models.CharField(blank=True, default='', max_length=9, null=True)),
                ('teammate1_thapar_email', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(max_length=22)),
                ('leader_roll_no', models.CharField(max_length=9)),
                ('leader_thapar_email', models.CharField(max_length=50)),
                ('leader_phone_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(max_length=22)),
                ('leader_roll_no', models.CharField(max_length=9)),
                ('leader_thapar_email', models.CharField(max_length=50)),
                ('leader_phone_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, default='', max_length=12, null=True)),
                ('leader_name', models.CharField(max_length=22)),
                ('leader_roll_no', models.CharField(max_length=9)),
                ('leader_thapar_email', models.CharField(max_length=50)),
                ('teammate1_name', models.CharField(max_length=22)),
                ('teammate1_roll_no', models.CharField(max_length=9)),
                ('teammate1_thapar_email', models.CharField(max_length=50)),
                ('teammate2_name', models.CharField(max_length=22)),
                ('teammate2_roll_no', models.CharField(max_length=9)),
                ('teammate2_thapar_email', models.CharField(max_length=50)),
            ],
        ),
    ]
