# Generated by Django 4.0.2 on 2023-03-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_clowncanard_codeoclock_movie_speaker_wtb'),
    ]

    operations = [
        migrations.AddField(
            model_name='clowncanard',
            name='leader_phone_no',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clowncanard',
            name='teammate1_phone_no',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clowncanard',
            name='teammate2_phone_no',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='codeoclock',
            name='leader_phone_no',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codeoclock',
            name='teammate1_phone_no',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pteam',
            name='leader_phone_no',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pteam',
            name='teammate1_phone_no',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pteam',
            name='teammate2_phone_no',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wtb',
            name='leader_phone_no',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wtb',
            name='teammate1_phone_no',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wtb',
            name='teammate2_phone_no',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
